# Configuration of Hugo
# Website name (set in params.yaml under hugoblox.identity.name)
title: 'Shechter Lab'
baseURL: 'https://www.shechterlab.org/'

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  anchor: smart
  jpeg:
    quality: 90
  webp:
    quality: 90
    hint: picture
  avif:
    quality: 90
    hint: picture
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
